import type { Roadmap, Lesson, DeeperTopic, LearnerProfile } from "../types";

// Deterministic placeholder generator used while the real backend is being
// built (Step 1). It fabricates plausibly-shaped content so the full UI loop
// — Explore → calibrate → roadmap → lesson → go deeper → progress — is
// clickable end-to-end with no API key and no network. Replaced by the
// Netlify Functions in Step 2.

const delay = (ms: number) => new Promise((r) => setTimeout(r, ms));
let counter = 0;
const uid = (p: string) => `${p}_${Date.now()}_${counter++}`;

export async function generateStubRoadmap(
  topic: string,
  profile: LearnerProfile,
): Promise<Roadmap> {
  await delay(700);
  const phaseNames = ["Foundations", "Core Concepts", "Applied Practice", "Mastery"];
  return {
    id: uid("r"),
    topic,
    profile,
    title: topic.replace(/\b\w/g, (c) => c.toUpperCase()),
    description: `A structured path to go from your current level to confident, applied understanding of ${topic}.`,
    level: profile.familiarity.includes("Advanced")
      ? "Advanced"
      : profile.familiarity.includes("beginner")
        ? "Beginner"
        : "Intermediate",
    timeEstimate: "4–6 weeks at 30 min/day",
    outcomes: [
      `Explain the core ideas behind ${topic} in plain language`,
      `Apply ${topic} to a concrete, real-world problem`,
      `Build something small and complete using ${topic}`,
    ],
    phases: phaseNames.map((name) => ({
      id: uid("p"),
      title: name,
      nodes: Array.from({ length: 4 }, (_, ni) => ({
        id: uid("n"),
        title: `${name}: concept ${ni + 1}`,
      })),
    })),
  };
}

export async function generateStubLesson(nodeTitle: string): Promise<Lesson> {
  await delay(600);
  return {
    lessonText: `This is placeholder lesson content for "${nodeTitle}". In the real app this is generated by Claude, personalised to your calibration answers, and served from cache when identical requests repeat.`,
    example: `A short worked example illustrating "${nodeTitle}" would appear here, grounded in a concrete scenario.`,
    diagram: {
      type: "flow",
      title: `How "${nodeTitle}" fits together`,
      items: [
        { label: "Input", detail: "what you start with" },
        { label: "Process", detail: "the key transformation" },
        { label: "Output", detail: "the result you get" },
      ],
    },
    keyTerms: [
      { term: "Term A", def: "a concise placeholder definition" },
      { term: "Term B", def: "another concise definition" },
      { term: "Term C", def: "a third concise definition" },
    ],
    funFact: `A surprising fact about "${nodeTitle}" would go here.`,
    quiz: [
      {
        q: `Which statement about "${nodeTitle}" is correct?`,
        options: ["The correct option", "A distractor", "Another distractor"],
        answer: "The correct option",
      },
    ],
  };
}

export async function generateStubDeeper(nodeTitle: string): Promise<DeeperTopic[]> {
  await delay(500);
  return [1, 2, 3].map((i) => ({
    id: uid("d"),
    title: `${nodeTitle} — advanced ${i}`,
  }));
}
